-- AgentMux event schema (Phase 7.1: the agent event foundation).
--
-- What this table is for, and what it is not.
--
-- An event records that something happened. It is not a status, not a current
-- value, and not a summary: the questions this table answers are "what has
-- happened to this project" and "when", and every question of the form "what is
-- true now" belongs to the layer that owns the thing being asked about. A
-- runtime's state is in project_runtime and in the runtime manager's memory; a
-- row here saying "running" would be a claim about a process, written once and
-- read much later, which is exactly the mistake migration 0002 refuses to make
-- with an is_running column.
--
-- Rows are append-only. Nothing in Phase 7.1 updates or deletes one and there is
-- no API that could: a history that can be edited is not a history. That is also
-- why the payload is bounded and why no error string is copied into it - a row
-- that can never be changed is a row that can never be redacted either.

CREATE TABLE IF NOT EXISTS agent_events (
    -- The event's identity: "evt_" followed by 128 random bits in hex.
    --
    -- Generated by the server rather than by the database, because identity the
    -- storage engine hands out is identity only the storage engine knows: two
    -- installations writing to two databases cannot agree on an integer, and an
    -- event that has to be stored before it can be named cannot be logged or
    -- queued before it is written.
    id         TEXT NOT NULL PRIMARY KEY,

    -- The project this happened to. Always present.
    project_id TEXT NOT NULL,

    -- The runtime this happened to, or NULL when the event is about the project
    -- rather than about a runtime. It holds the runtime's session name, which is
    -- the name the runtime has on the host and the one Destroy and Reconcile
    -- address it by.
    --
    -- Stored per event rather than derived from project_id at read time, for the
    -- reason migration 0002 gives for storing session_name: it is derivable
    -- today, and storing it means a change to the naming rule cannot make an
    -- existing row unreachable or quietly misleading.
    runtime_id TEXT,

    -- What happened, in a dotted namespace: 'runtime.started',
    -- 'runtime.stopped', 'runtime.error', 'runtime.destroyed'.
    --
    -- Validated by the service for shape rather than against a list. The
    -- vocabulary of what can happen belongs to the layers that find out, and an
    -- allowlist in a migration would make adding a type a schema change.
    type       TEXT NOT NULL,

    -- Who or what produced it: 'runtime', 'user', 'system', 'agent'. A closed
    -- set, checked at the write: a misspelled source is an event no filter ever
    -- matches, which is worse than a rejection.
    source     TEXT NOT NULL,

    -- Structured detail as JSON text, or NULL. Bounded at 4 KiB by the service.
    -- Deliberately small - this is a fact, not a document - and deliberately
    -- never a place for terminal output or a credential.
    payload    TEXT,

    -- When it happened, UTC, RFC3339 with nanoseconds, like every other
    -- timestamp in this database.
    created_at TEXT NOT NULL,

    -- An event about a project that no longer exists is unreachable through
    -- every endpoint this API has, so the rows would be unbounded garbage rather
    -- than history. Nothing in this build deletes a project, so nothing
    -- exercises this today; the constraint is here so that the day something
    -- does, it decides the question instead of leaving rows behind.
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE

    -- There is deliberately no foreign key on runtime_id. The project_runtime
    -- row is deleted when a runtime is destroyed, and "this runtime was
    -- destroyed" has to outlive it - a cascade there would delete the history of
    -- the very thing it was recording.
);

-- The query every consumer starts from: one project's timeline, newest first.
CREATE INDEX IF NOT EXISTS idx_agent_events_project
    ON agent_events (project_id, created_at DESC, id DESC);

-- One project's runtime across the restarts and destructions it has been
-- through. Not a foreign key, but still a column something will filter on.
CREATE INDEX IF NOT EXISTS idx_agent_events_runtime
    ON agent_events (runtime_id, created_at DESC, id DESC);

-- Ordering, which every read does and which no index can be left out of.
CREATE INDEX IF NOT EXISTS idx_agent_events_created
    ON agent_events (created_at DESC, id DESC);

-- "Every time a runtime failed" is a question somebody will ask of a table they
-- cannot easily scan by hand.
CREATE INDEX IF NOT EXISTS idx_agent_events_type
    ON agent_events (type, created_at DESC);
