-- AgentMux task schema (Phase 7.2: the task and agent session model).
--
-- What this table is for.
--
-- A task is a piece of work somebody wants an agent to do. It is not a
-- terminal, not a runtime, not a WebSocket and not a Claude process: it is the
-- thing those exist to serve, and it outlives every one of them.
--
-- The distinction is easiest to see as two questions with different tenses.
-- "Is the terminal up?" is answered by project_runtime and by the runtime
-- manager's memory, and it stops meaning anything once the process exits. "Was
-- this work finished?" is answered here, and it stays true after every process
-- involved has exited, been destroyed and been forgotten.
--
-- docs/TASK_MODEL.md is the long form.

CREATE TABLE IF NOT EXISTS tasks (
    -- The task's identity: "task_" followed by 96 random bits in hex.
    --
    -- Generated by the server rather than by the database, for the reason every
    -- identifier in this schema is: identity the storage engine hands out is
    -- identity only the storage engine knows, and a row that has to be stored
    -- before it can be named cannot be logged before it is written.
    id          TEXT NOT NULL PRIMARY KEY,

    -- The project this work belongs to. Always present.
    project_id  TEXT NOT NULL,

    -- What somebody wants done, in their own words.
    --
    -- Free text, bounded at 200 characters by the service. It is never
    -- executed, never interpolated into a shell, and never interpreted as a
    -- path or as HTML: it is stored and returned as an opaque string, and
    -- escaping it for display is the display layer's job.
    --
    -- It is deliberately NOT copied into agent_events. A title is the one field
    -- in this table a person wrote, and a row that can never be edited can
    -- never be redacted either.
    title       TEXT NOT NULL,

    -- 'CREATED', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED' or 'CANCELLED'.
    --
    -- This is a status and not a history, which is the difference between this
    -- column and agent_events: it is overwritten by the next value, and it is
    -- the authority on what is true now. Events record what happened; this
    -- column says what is.
    --
    -- The lifecycle is enforced in the service, not by a CHECK constraint,
    -- because the rule has to name which transitions were available in its
    -- refusal and a constraint cannot. See docs/TASK_MODEL.md §2.
    status      TEXT NOT NULL,

    created_at  TEXT NOT NULL,

    -- Moves on a status change and on a retitle.
    updated_at  TEXT NOT NULL,

    -- When the task entered COMPLETED, and NULL otherwise.
    --
    -- It is cleared when a task is not completed, so a FAILED task carries no
    -- completion time. Nothing was completed, and a stale timestamp would be a
    -- claim that something was.
    completed_at TEXT,

    -- A task without its project is unreachable through every endpoint this API
    -- has - a task is listed under its project and nothing lists it by id
    -- alone - so the rows would be garbage rather than history.
    --
    -- Nothing in this build deletes a project, and there is no endpoint that
    -- could. The constraint is here so that the day something does, it decides
    -- the question instead of leaving rows behind. It cascades to
    -- agent_sessions and deliberately NOT to agent_events: the event log is an
    -- independent append-only history, keyed by project and runtime rather than
    -- by task, and Phase 7.1's guarantee that a history cannot be deleted is
    -- not weakened by this phase.
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

-- One project's tasks, newest first. The query every consumer starts from.
CREATE INDEX IF NOT EXISTS idx_tasks_project
    ON tasks (project_id, created_at DESC, id DESC);

-- "Which of this project's tasks are still running" is the question a task
-- screen will ask first, and it is not answerable from the index above.
CREATE INDEX IF NOT EXISTS idx_tasks_status
    ON tasks (status, created_at DESC);

-- Ordering across projects, which the status index above does not provide on
-- its own.
CREATE INDEX IF NOT EXISTS idx_tasks_created
    ON tasks (created_at DESC, id DESC);
