-- AgentMux beta usage events (Phase 7.5).
--
-- What the deployment did, counted. One row per occurrence of one of five
-- things:
--
--     dashboard.open       a browser asked for the console page
--     terminal.connect     a browser subscribed to a project's terminal
--     controller.request   a client asked for a project's control lease
--     controller.release   a client gave one up
--     action.view          a browser asked for one action's page
--
-- # What this table deliberately is not
--
-- It is not a log and it is not an audit trail. It records no actor, no project,
-- no session and no device: there is no column for any of them, so no query
-- against it can answer "who did what" even by accident.
--
-- It carries no payload, and there is no column one could go in. That is the
-- whole of §八 of the phase brief - no terminal content, no prompt, no input, no
-- Claude output - and the guarantee is the schema rather than a filter. The way
-- to keep that promise is a table with nowhere to put those things, not a
-- cleaner looking for four kinds of string. agent_attention's `reason` column
-- takes the same position for the same reason: it is a fixed phrase, not a
-- quotation, so a payload cannot become a reason by being long enough.
--
-- It is server-observed. Nothing writes here from a request body, and there is
-- no endpoint that accepts one. Every row is written by the code path its
-- event_type names, and the only thing a client can influence is whether that
-- path ran.
--
-- The rows are deletable without loss. Nothing derives anything from this table
-- and nothing reads it to decide anything, so a beta that ends by truncating it
-- has lost a count and nothing else.

CREATE TABLE IF NOT EXISTS usage_events (
    -- The event's identity, generated by the server before the row exists.
    --
    -- Nothing addresses a usage event by id - there is no URL, no cursor and no
    -- endpoint that reads one - so this is an identifier of record rather than
    -- a handle. See internal/usage for the width it is generated at.
    id         TEXT NOT NULL PRIMARY KEY,

    -- One of the five dotted names above.
    --
    -- It is TEXT and not a CHECK constraint, because the vocabulary lives in
    -- internal/usage and a constraint here would be a second copy of it that
    -- could drift. The vocabulary is enforced where the row is written, and a
    -- value that is not one of the five is refused there rather than stored and
    -- discovered here.
    event_type TEXT NOT NULL,

    -- When the server recorded it, RFC 3339 UTC with nanoseconds.
    --
    -- It is the recording time and nothing else. There is no event time
    -- supplied by anybody, because there is nobody on the other end of this to
    -- supply one and nothing to trust if there were.
    created_at TEXT NOT NULL
);

-- The one index.
--
-- A usage table is read as a time series - "what happened in the last week of
-- the beta" - and adding an index to a populated table later is the expensive
-- moment. It is on created_at alone: nothing has ever asked this table a
-- question by event_type, and an index for a query nobody writes is a cost with
-- no answer.
CREATE INDEX IF NOT EXISTS idx_usage_events_created_at ON usage_events (created_at);
